name: 🛠️ Builds
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - identifier: android-debug-arm64
            name: Android Debug arm64
            runner: ubuntu-22.04
            target: template_debug
            platform: android
            arch: arm64
          - identifier: android-release-arm64
            name: Android Release arm64
            runner: ubuntu-22.04
            target: template_release
            platform: android
            arch: arm64
    steps:
      - name: (Android) Install JDK 17
        if: ${{ matrix.platform == 'android' }}
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: (Android) Install Android SDK
        if: ${{ matrix.platform == 'android' }}
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true

      - name: (Android) Install Exact NDK Required by Godot
        if: ${{ matrix.platform == 'android' }}
        shell: bash
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;28.1.13356709"

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install SCons
        shell: bash
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          scons --version

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up SCons cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.scons-cache/
            ${{ github.workspace }}/**/.sconsign.dblite
            ${{ github.workspace }}/godot-cpp/gen/
          key: ${{ matrix.identifier }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ matrix.identifier }}-${{ github.ref }}-${{ github.sha }}
            ${{ matrix.identifier }}-${{ github.ref }}-
            ${{ matrix.identifier }}-

      - name: Compile extension
        shell: bash
        env:
          SCONS_CACHE: '${{ github.workspace }}/.scons-cache/'
          SCONS_CACHE_LIMIT: 4096
        run: |
          if [ "${{ matrix.platform }}" = "android" ]; then
            export ANDROID_NDK_ROOT="${ANDROID_SDK_ROOT}/ndk/28.1.13356709"
            echo "Using ANDROID_NDK_ROOT: $ANDROID_NDK_ROOT"

            export NDK_TOOLCHAIN="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin"
            export PATH="$NDK_TOOLCHAIN:$PATH"
          fi

          if [ "${{ matrix.arch }}" = "arm64" ]; then
           export API_LEVEL=24
           export CC="$NDK_TOOLCHAIN/aarch64-linux-android${API_LEVEL}-clang"
           export CXX="$NDK_TOOLCHAIN/aarch64-linux-android${API_LEVEL}-clang++"
           export AR="$NDK_TOOLCHAIN/llvm-ar"
           export RANLIB="$NDK_TOOLCHAIN/llvm-ranlib"
          fi
          # 1. Explicitly build godot-cpp first to generate missing headers (.hpp files)
          cd godot-cpp
          scons target='${{ matrix.target }}' platform='${{ matrix.platform }}' arch='${{ matrix.arch }}' -j2
          cd ..
          
          # 2. Build the top level patcher extension
          scons target='${{ matrix.target }}' platform='${{ matrix.platform }}' arch='${{ matrix.arch }}' -j2
          ls -l project/addons/*/bin/

      - name: Copy README.md and LICENSE to addon and make a new directory for artifacts
        shell: bash
        run: |
          for addon in ${{ github.workspace }}/project/addons/*/; do
            cp --no-clobber '${{ github.workspace }}/README.md' '${{ github.workspace }}/LICENSE' "$addon"
          done
          mkdir --parents ${{ github.workspace }}/github-artifact/${{ github.event.repository.name }}-${{ github.sha }}/
          mv ${{ github.workspace }}/project/addons/ ${{ github.workspace }}/github-artifact/${{ github.event.repository.name }}-${{ github.sha }}/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.identifier }}
          path: |
            ${{ github.workspace }}/github-artifact

  merge:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: ${{ github.event.repository.name }}-${{ github.event_name == 'pull_request' && format('pr{0}', github.event.number) || github.ref_name }}
          delete-merged: true
